#!/usr/bin/env python3
import os
import sys
from datetime import datetime

dirname = os.path.expanduser(r'~/Scripts')
try:
    dirname = os.path.expanduser(sys.argv[1])
except:
    print('Usage: fester <path of directory>')
    sys.exit()
    
files = os.listdir(dirname)
dt = datetime.now()
on = dt.strftime('%m/%d/%Y')
at = dt.strftime('%H:%M')
stamp = f'Created on {on} at {at} \n'
cont = f'Contents of {dirname}: \n'
for file in files:
    formatted = f'* {file} \n'
    cont = cont + formatted
out = open(f'{dirname}/manifest.md', 'w')
out.write(cont)
out.close()